# yaml-language-server: $schema=../node_modules/somod-schema/schemas/serverless-template/index.json

Resources:
  AjvLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      RetentionPolicy: Delete
      ContentUri:
        SOMOD::FunctionLayer:
          name: ajvLayer
          libraries:
            - decorated-ajv
  SomodHttpMiddleware:
    Type: SOMOD::Serverless::FunctionMiddleware
    SOMOD::Access: public
    Properties:
      CodeUri:
        SOMOD::FunctionMiddleware:
          name: httpMiddleware
          allowedTypes:
            - HttpApi
            - WebSocket
      Layers:
        - SOMOD::Ref:
            resource: AjvLayer
      Environment:
        Variables:
          SOMOD_HTTP_LOG_4XX:
            SOMOD::Parameter: http.log.4xx
